# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e755e1843037cc1f0eeddc9ea9948acbae500466bd8ab7d2636cdce7010493766bd060c9c0247ebb5cd12032479c247941a4cf9a7131dfe242e060a03d0ca07e

test:
  secret_key_base: 82c0016a580cbf5704f9364c5fb7b81d8042d3d0fedf055563243b4bbd0b17f40d7e5e8eeb7d552d3e034c278409ed949c3a9c3dad8b67fe5da22dc2a2d7eb82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
